spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  batch:
    job:
      enabled: true
    jdbc:
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
      initialize-schema: always