
server:
  port: 28080
nacos:
  discovery:
    auto-register: true
  config:
    bootstrap:
      enable: true
    type: properties
    auto-refresh: true
    max-retry: 10
    config-retry-time: 1000
    config-long-poll-timeout: 60000
    data-id: nacos-config
    group: nacos
    server-addr: 127.0.0.1:8848